"""added published updated on recommendation

Revision ID: c9d440471e0e
Revises: f4f186953d09
Create Date: 2023-08-01 15:07:24.317103

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c9d440471e0e'
down_revision = 'f4f186953d09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('published', sa.DateTime(), nullable=True))
    op.add_column('recommendation', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation', 'updated')
    op.drop_column('recommendation', 'published')
    # ### end Alembic commands ###
